name: EssentialReplace
main: io.github.sweetenpotato.Main
version: 1.0.0
description: The soft version of Essential
authors: [sweetenpotato]
commands:
  spawn:
    description: Move to spawn.
    usage: /spawn